//
// File generated by rootcint at Tue Jun  4 15:20:36 2019

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME WFCTADecodeDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "WFCTADecodeDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void WFCTADecode_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_WFCTADecode(void *p = 0);
   static void *newArray_WFCTADecode(Long_t size, void *p);
   static void delete_WFCTADecode(void *p);
   static void deleteArray_WFCTADecode(void *p);
   static void destruct_WFCTADecode(void *p);
   static void streamer_WFCTADecode(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::WFCTADecode*)
   {
      ::WFCTADecode *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::WFCTADecode >(0);
      static ::ROOT::TGenericClassInfo 
         instance("WFCTADecode", ::WFCTADecode::Class_Version(), "./WFCTADecode.h", 13,
                  typeid(::WFCTADecode), DefineBehavior(ptr, ptr),
                  &::WFCTADecode::Dictionary, isa_proxy, 0,
                  sizeof(::WFCTADecode) );
      instance.SetNew(&new_WFCTADecode);
      instance.SetNewArray(&newArray_WFCTADecode);
      instance.SetDelete(&delete_WFCTADecode);
      instance.SetDeleteArray(&deleteArray_WFCTADecode);
      instance.SetDestructor(&destruct_WFCTADecode);
      instance.SetStreamerFunc(&streamer_WFCTADecode);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::WFCTADecode*)
   {
      return GenerateInitInstanceLocal((::WFCTADecode*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::WFCTADecode*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *WFCTADecode::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *WFCTADecode::Class_Name()
{
   return "WFCTADecode";
}

//______________________________________________________________________________
const char *WFCTADecode::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::WFCTADecode*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int WFCTADecode::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::WFCTADecode*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void WFCTADecode::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::WFCTADecode*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *WFCTADecode::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::WFCTADecode*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void WFCTADecode::Streamer(TBuffer &R__b)
{
   // Stream an object of class WFCTADecode.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      R__b >> head;
      R__b >> tail;
      R__b >> readPos;
      R__b >> status_pack_mark;
      R__b >> packSize;
      {
         map<short,int> &R__stl =  m_sipm_position;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         for (R__i = 0; R__i < R__n; R__i++) {
            short R__t;
            R__b >> R__t;
            int R__t2;
            R__b >> R__t2;
            typedef short Value_t;
            std::pair<Value_t const, int > R__t3(R__t,R__t2);
            R__stl.insert(R__t3);
         }
      }
      R__b.StreamObject(&(m_sipm_position_iter),typeid(map<short,int,less<short>,allocator<pair<const short,int> > >::iterator));
      R__b >> m_adc_high;
      R__b >> m_adc_low;
      R__b >> m_base_high;
      R__b >> m_base_low;
      R__b >> m_Basehigh;
      R__b >> m_Baselow;
      R__b >> m_Adchigh;
      R__b >> m_Adclow;
      R__b >> m_mypeak;
      R__b.ReadStaticArray((int*)pulsehigh);
      R__b.ReadStaticArray((int*)pulselow);
      R__b.CheckByteCount(R__s, R__c, WFCTADecode::IsA());
   } else {
      R__c = R__b.WriteVersion(WFCTADecode::IsA(), kTRUE);
      R__b << head;
      R__b << tail;
      R__b << readPos;
      R__b << status_pack_mark;
      R__b << packSize;
      {
         map<short,int> &R__stl =  m_sipm_position;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            map<short,int>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << ((*R__k).first );
            R__b << ((*R__k).second);
            }
         }
      }
      R__b.StreamObject(&(m_sipm_position_iter),typeid(map<short,int,less<short>,allocator<pair<const short,int> > >::iterator));
      R__b << m_adc_high;
      R__b << m_adc_low;
      R__b << m_base_high;
      R__b << m_base_low;
      R__b << m_Basehigh;
      R__b << m_Baselow;
      R__b << m_Adchigh;
      R__b << m_Adclow;
      R__b << m_mypeak;
      R__b.WriteArray(pulsehigh, 32);
      R__b.WriteArray(pulselow, 32);
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void WFCTADecode::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class WFCTADecode.
      TClass *R__cl = ::WFCTADecode::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "head", &head);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tail", &tail);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "readPos", &readPos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "status_pack_mark", &status_pack_mark);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "packSize", &packSize);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_sipm_position", (void*)&m_sipm_position);
      R__insp.InspectMember("map<short,int>", (void*)&m_sipm_position, "m_sipm_position.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_sipm_position_iter", (void*)&m_sipm_position_iter);
      R__insp.InspectMember("map<short,int,less<short>,allocator<pair<const short,int> > >::iterator", (void*)&m_sipm_position_iter, "m_sipm_position_iter.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_adc_high", &m_adc_high);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_adc_low", &m_adc_low);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_base_high", &m_base_high);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_base_low", &m_base_low);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Basehigh", &m_Basehigh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Baselow", &m_Baselow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Adchigh", &m_Adchigh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_Adclow", &m_Adclow);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_mypeak", &m_mypeak);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pulsehigh[32]", pulsehigh);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "pulselow[32]", pulselow);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_WFCTADecode(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::WFCTADecode : new ::WFCTADecode;
   }
   static void *newArray_WFCTADecode(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::WFCTADecode[nElements] : new ::WFCTADecode[nElements];
   }
   // Wrapper around operator delete
   static void delete_WFCTADecode(void *p) {
      delete ((::WFCTADecode*)p);
   }
   static void deleteArray_WFCTADecode(void *p) {
      delete [] ((::WFCTADecode*)p);
   }
   static void destruct_WFCTADecode(void *p) {
      typedef ::WFCTADecode current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_WFCTADecode(TBuffer &buf, void *obj) {
      ((::WFCTADecode*)obj)->::WFCTADecode::Streamer(buf);
   }
} // end of namespace ROOT for class ::WFCTADecode

namespace ROOT {
   void maplEshortcOintgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void maplEshortcOintgR_Dictionary();
   static void *new_maplEshortcOintgR(void *p = 0);
   static void *newArray_maplEshortcOintgR(Long_t size, void *p);
   static void delete_maplEshortcOintgR(void *p);
   static void deleteArray_maplEshortcOintgR(void *p);
   static void destruct_maplEshortcOintgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const map<short,int>*)
   {
      map<short,int> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(map<short,int>),0);
      static ::ROOT::TGenericClassInfo 
         instance("map<short,int>", -2, "prec_stl/map", 63,
                  typeid(map<short,int>), DefineBehavior(ptr, ptr),
                  0, &maplEshortcOintgR_Dictionary, isa_proxy, 0,
                  sizeof(map<short,int>) );
      instance.SetNew(&new_maplEshortcOintgR);
      instance.SetNewArray(&newArray_maplEshortcOintgR);
      instance.SetDelete(&delete_maplEshortcOintgR);
      instance.SetDeleteArray(&deleteArray_maplEshortcOintgR);
      instance.SetDestructor(&destruct_maplEshortcOintgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::MapInsert< map<short,int> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const map<short,int>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void maplEshortcOintgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const map<short,int>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_maplEshortcOintgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) map<short,int> : new map<short,int>;
   }
   static void *newArray_maplEshortcOintgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) map<short,int>[nElements] : new map<short,int>[nElements];
   }
   // Wrapper around operator delete
   static void delete_maplEshortcOintgR(void *p) {
      delete ((map<short,int>*)p);
   }
   static void deleteArray_maplEshortcOintgR(void *p) {
      delete [] ((map<short,int>*)p);
   }
   static void destruct_maplEshortcOintgR(void *p) {
      typedef map<short,int> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class map<short,int>

/********************************************************
* WFCTADecodeDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableWFCTADecodeDict();

extern "C" void G__set_cpp_environmentWFCTADecodeDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("WFCTADecode.h");
  G__cpp_reset_tagtableWFCTADecodeDict();
}
#include <new>
extern "C" int G__cpp_dllrevWFCTADecodeDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* WFCTADecode */
static int G__WFCTADecodeDict_419_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   WFCTADecode* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new WFCTADecode[n];
     } else {
       p = new((void*) gvp) WFCTADecode[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new WFCTADecode;
     } else {
       p = new((void*) gvp) WFCTADecode;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 98, (long) ((WFCTADecode*) G__getstructoffset())->StatusPackCheck((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((WFCTADecode*) G__getstructoffset())->bigPackCheck((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->Find_SiPMs((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((WFCTADecode*) G__getstructoffset())->PackSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         const map<short,int>& obj = ((WFCTADecode*) G__getstructoffset())->GetSiPM_Position();
         result7->ref = (long) (&obj);
         result7->obj.i = (long) (&obj);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((WFCTADecode*) G__getstructoffset())->eventId((uint8_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((WFCTADecode*) G__getstructoffset())->RabbitTime((uint8_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((WFCTADecode*) G__getstructoffset())->Rabbittime((uint8_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 98, (long) ((WFCTADecode*) G__getstructoffset())->GetPeak((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((WFCTADecode*) G__getstructoffset())->Getgain_marker((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 98, (long) ((WFCTADecode*) G__getstructoffset())->Getmypeak((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((WFCTADecode*) G__getstructoffset())->GetSingle_Thresh((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 114, (long) ((WFCTADecode*) G__getstructoffset())->GetRecord_Thresh((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((WFCTADecode*) G__getstructoffset())->GetOver_Single_Mark((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((WFCTADecode*) G__getstructoffset())->GetOver_Record_Mark((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->GetADC_Cut((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->AdcHigh((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->AdcLow((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->BaseHigh((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->BaseLow((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->GetmyImageBaseHigh((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->GetmyImageBaseLow((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->GetmyImageAdcHigh((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((WFCTADecode*) G__getstructoffset())->GetmyImageAdcLow((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->GetWaveForm((uint8_t*) G__int(libp->para[0]), (short) G__int(libp->para[1])
, (int*) G__int(libp->para[2]), (int*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->Getthresh((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (short*) G__int(libp->para[2]), (short*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->Deal22Pack((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (long*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->Deal23Pack((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (long*) G__int(libp->para[2]), (long*) G__int(libp->para[3]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->GetHV((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->GetPreTemp((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->GetClbTemp((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (float*) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((WFCTADecode*) G__getstructoffset())->GetclbInitialTime((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((WFCTADecode*) G__getstructoffset())->GetclbInitialtime((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((WFCTADecode*) G__getstructoffset())->GetFiredTube((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 107, (long) ((WFCTADecode*) G__getstructoffset())->GetStatusReadbackTime((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((WFCTADecode*) G__getstructoffset())->GetStatusReadbacktime((uint8_t*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) WFCTADecode::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) WFCTADecode::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) WFCTADecode::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_43(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      WFCTADecode::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const WFCTADecode*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((WFCTADecode*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_48(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) WFCTADecode::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_49(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) WFCTADecode::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_50(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) WFCTADecode::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__WFCTADecodeDict_419_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) WFCTADecode::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__WFCTADecodeDict_419_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   WFCTADecode* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new WFCTADecode(*(WFCTADecode*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef WFCTADecode G__TWFCTADecode;
static int G__WFCTADecodeDict_419_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (WFCTADecode*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((WFCTADecode*) (soff+(sizeof(WFCTADecode)*i)))->~G__TWFCTADecode();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (WFCTADecode*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((WFCTADecode*) (soff))->~G__TWFCTADecode();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__WFCTADecodeDict_419_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   WFCTADecode* dest = (WFCTADecode*) G__getstructoffset();
   *dest = *(WFCTADecode*) libp->para[0].ref;
   const WFCTADecode& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* WFCTADecode */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncWFCTADecodeDict {
 public:
  G__Sizep2memfuncWFCTADecodeDict(): p(&G__Sizep2memfuncWFCTADecodeDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncWFCTADecodeDict::*p)();
};

size_t G__get_sizep2memfuncWFCTADecodeDict()
{
  G__Sizep2memfuncWFCTADecodeDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceWFCTADecodeDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableWFCTADecodeDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint8_t",98,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint16_t",114,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("uint64_t",107,-1,0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<short,int>",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<short,int,less<short> >",117,G__get_linked_tagnum(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* WFCTADecode */
static void G__setup_memvarWFCTADecode(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode));
   { WFCTADecode *p; p=(WFCTADecode*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("int64_t"),-1,4,"head=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("int64_t"),-1,4,"tail=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("int64_t"),-1,4,"readPos=",0,(char*)NULL);
   G__memvar_setup((void*)0,98,0,0,-1,G__defined_typename("uint8_t"),-1,4,"status_pack_mark=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,G__defined_typename("int64_t"),-1,4,"packSize=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR),G__defined_typename("map<short,int>"),-1,4,"m_sipm_position=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgRcLcLiterator),-1,-1,4,"m_sipm_position_iter=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_adc_high=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_adc_low=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_base_high=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_base_low=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_Basehigh=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_Baselow=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_Adchigh=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"m_Adclow=",0,(char*)NULL);
   G__memvar_setup((void*)0,98,0,0,-1,G__defined_typename("uint8_t"),-1,4,"m_mypeak=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"pulsehigh[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"pulselow[32]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__WFCTADecodeDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarWFCTADecodeDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncWFCTADecode(void) {
   /* WFCTADecode */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode));
   G__memfunc_setup("WFCTADecode",953,G__WFCTADecodeDict_419_0_1, 105, G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("StatusPackCheck",1505,G__WFCTADecodeDict_419_0_2, 98, -1, G__defined_typename("uint8_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - bufsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("bigPackCheck",1167,G__WFCTADecodeDict_419_0_3, 103, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - bufsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Find_SiPMs",940,G__WFCTADecodeDict_419_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PackSize",794,G__WFCTADecodeDict_419_0_5, 107, -1, G__defined_typename("uint64_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSiPM_Position",1581,G__WFCTADecodeDict_419_0_6, 117, G__get_linked_tagnum(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR), G__defined_typename("map<short,int>"), 1, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("eventId",719,G__WFCTADecodeDict_419_0_7, 107, -1, G__defined_typename("uint64_t"), 0, 1, 1, 1, 0, "B - 'uint8_t' 0 - begin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("RabbitTime",995,G__WFCTADecodeDict_419_0_8, 107, -1, G__defined_typename("uint64_t"), 0, 1, 1, 1, 0, "B - 'uint8_t' 0 - begin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Rabbittime",1027,G__WFCTADecodeDict_419_0_9, 100, -1, -1, 0, 1, 1, 1, 0, "B - 'uint8_t' 0 - begin", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPeak",673,G__WFCTADecodeDict_419_0_10, 98, -1, G__defined_typename("uint8_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Getgain_marker",1440,G__WFCTADecodeDict_419_0_11, 103, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Getmypeak",935,G__WFCTADecodeDict_419_0_12, 98, -1, G__defined_typename("uint8_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSingle_Thresh",1615,G__WFCTADecodeDict_419_0_13, 114, -1, G__defined_typename("uint16_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetRecord_Thresh",1612,G__WFCTADecodeDict_419_0_14, 114, -1, G__defined_typename("uint16_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOver_Single_Mark",1895,G__WFCTADecodeDict_419_0_15, 103, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetOver_Record_Mark",1892,G__WFCTADecodeDict_419_0_16, 103, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetADC_Cut",883,G__WFCTADecodeDict_419_0_17, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AdcHigh",648,G__WFCTADecodeDict_419_0_18, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("AdcLow",570,G__WFCTADecodeDict_419_0_19, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BaseHigh",763,G__WFCTADecodeDict_419_0_20, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("BaseLow",685,G__WFCTADecodeDict_419_0_21, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetmyImageBaseHigh",1764,G__WFCTADecodeDict_419_0_22, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetmyImageBaseLow",1686,G__WFCTADecodeDict_419_0_23, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetmyImageAdcHigh",1649,G__WFCTADecodeDict_419_0_24, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetmyImageAdcLow",1571,G__WFCTADecodeDict_419_0_25, 102, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetWaveForm",1095,G__WFCTADecodeDict_419_0_26, 121, -1, -1, 0, 4, 1, 1, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm "
"I - - 0 - pulseh I - - 0 - pulsel", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Getthresh",942,G__WFCTADecodeDict_419_0_27, 121, -1, -1, 0, 4, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize "
"S - - 0 - single_thresh S - - 0 - record_thresh", "Deal21Package", (void*) NULL, 0);
   G__memfunc_setup("Deal22Pack",857,G__WFCTADecodeDict_419_0_28, 121, -1, -1, 0, 3, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize "
"L - - 0 - single_count", "Deal22Package", (void*) NULL, 0);
   G__memfunc_setup("Deal23Pack",858,G__WFCTADecodeDict_419_0_29, 121, -1, -1, 0, 4, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize "
"L - - 0 - single_count L - - 0 - single_time", "Deal23Package", (void*) NULL, 0);
   G__memfunc_setup("GetHV",446,G__WFCTADecodeDict_419_0_30, 121, -1, -1, 0, 3, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize "
"F - - 0 - HV", "Deal81Package", (void*) NULL, 0);
   G__memfunc_setup("GetPreTemp",989,G__WFCTADecodeDict_419_0_31, 121, -1, -1, 0, 3, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize "
"F - - 0 - PreTemp", "Deal82Package", (void*) NULL, 0);
   G__memfunc_setup("GetClbTemp",967,G__WFCTADecodeDict_419_0_32, 121, -1, -1, 0, 3, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize "
"F - - 0 - ClbTemp", "Deal85pack", (void*) NULL, 0);
   G__memfunc_setup("GetclbInitialTime",1706,G__WFCTADecodeDict_419_0_33, 107, -1, G__defined_typename("uint64_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetclbInitialtime",1738,G__WFCTADecodeDict_419_0_34, 100, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetFiredTube",1178,G__WFCTADecodeDict_419_0_35, 105, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStatusReadbackTime",2112,G__WFCTADecodeDict_419_0_36, 107, -1, G__defined_typename("uint64_t"), 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStatusReadbacktime",2144,G__WFCTADecodeDict_419_0_37, 100, -1, -1, 0, 2, 1, 1, 0, 
"B - 'uint8_t' 0 - begin i - - 0 - packsize", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("waveform",871,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Calc_Q_Base",1021,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"B - 'uint8_t' 0 - begin s - - 0 - isipm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__WFCTADecodeDict_419_0_40, 85, G__get_linked_tagnum(&G__WFCTADecodeDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&WFCTADecode::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__WFCTADecodeDict_419_0_41, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&WFCTADecode::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__WFCTADecodeDict_419_0_42, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&WFCTADecode::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__WFCTADecodeDict_419_0_43, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&WFCTADecode::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__WFCTADecodeDict_419_0_44, 85, G__get_linked_tagnum(&G__WFCTADecodeDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__WFCTADecodeDict_419_0_45, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__WFCTADecodeDict_419_0_46, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__WFCTADecodeDict_419_0_47, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__WFCTADecodeDict_419_0_48, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&WFCTADecode::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__WFCTADecodeDict_419_0_49, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&WFCTADecode::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__WFCTADecodeDict_419_0_50, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&WFCTADecode::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__WFCTADecodeDict_419_0_51, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&WFCTADecode::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("WFCTADecode", 953, G__WFCTADecodeDict_419_0_52, (int) ('i'), G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode), -1, 0, 1, 1, 1, 0, "u 'WFCTADecode' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~WFCTADecode", 1079, G__WFCTADecodeDict_419_0_53, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__WFCTADecodeDict_419_0_54, (int) ('u'), G__get_linked_tagnum(&G__WFCTADecodeDictLN_WFCTADecode), -1, 1, 1, 1, 1, 0, "u 'WFCTADecode' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncWFCTADecodeDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalWFCTADecodeDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcWFCTADecodeDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__WFCTADecodeDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_WFCTADecode = { "WFCTADecode" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR = { "map<short,int,less<short>,allocator<pair<const short,int> > >" , 99 , -1 };
G__linked_taginfo G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgRcLcLiterator = { "map<short,int,less<short>,allocator<pair<const short,int> > >::iterator" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableWFCTADecodeDict() {
  G__WFCTADecodeDictLN_TClass.tagnum = -1 ;
  G__WFCTADecodeDictLN_TBuffer.tagnum = -1 ;
  G__WFCTADecodeDictLN_TMemberInspector.tagnum = -1 ;
  G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__WFCTADecodeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__WFCTADecodeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__WFCTADecodeDictLN_WFCTADecode.tagnum = -1 ;
  G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR.tagnum = -1 ;
  G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgRcLcLiterator.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableWFCTADecodeDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_WFCTADecode),sizeof(WFCTADecode),-1,1280,(char*)NULL,G__setup_memvarWFCTADecode,G__setup_memfuncWFCTADecode);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgRcLcLiterator);
}
extern "C" void G__cpp_setupWFCTADecodeDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupWFCTADecodeDict()");
  G__set_cpp_environmentWFCTADecodeDict();
  G__cpp_setup_tagtableWFCTADecodeDict();

  G__cpp_setup_inheritanceWFCTADecodeDict();

  G__cpp_setup_typetableWFCTADecodeDict();

  G__cpp_setup_memvarWFCTADecodeDict();

  G__cpp_setup_memfuncWFCTADecodeDict();
  G__cpp_setup_globalWFCTADecodeDict();
  G__cpp_setup_funcWFCTADecodeDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncWFCTADecodeDict();
  return;
}
class G__cpp_setup_initWFCTADecodeDict {
  public:
    G__cpp_setup_initWFCTADecodeDict() { G__add_setup_func("WFCTADecodeDict",(G__incsetup)(&G__cpp_setupWFCTADecodeDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initWFCTADecodeDict() { G__remove_setup_func("WFCTADecodeDict"); }
};
G__cpp_setup_initWFCTADecodeDict G__cpp_setup_initializerWFCTADecodeDict;

