/********************************************************************
* WFCTAEventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error WFCTAEventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWFCTAEventDict();
extern void G__cpp_setup_inheritanceWFCTAEventDict();
extern void G__cpp_setup_typetableWFCTAEventDict();
extern void G__cpp_setup_memvarWFCTAEventDict();
extern void G__cpp_setup_globalWFCTAEventDict();
extern void G__cpp_setup_memfuncWFCTAEventDict();
extern void G__cpp_setup_funcWFCTAEventDict();
extern void G__set_cpp_environmentWFCTAEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WFCTAEvent.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WFCTAEventDictLN_TClass;
extern G__linked_taginfo G__WFCTAEventDictLN_TBuffer;
extern G__linked_taginfo G__WFCTAEventDictLN_TMemberInspector;
extern G__linked_taginfo G__WFCTAEventDictLN_vectorlEcharcOallocatorlEchargRsPgR;
extern G__linked_taginfo G__WFCTAEventDictLN_vectorlEshortcOallocatorlEshortgRsPgR;
extern G__linked_taginfo G__WFCTAEventDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__WFCTAEventDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__WFCTAEventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WFCTAEventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WFCTAEventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WFCTAEventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WFCTAEventDictLN_WFCTAEvent;

/* STUB derived class for protected member access */
