/********************************************************************
* WFCTADecodeDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error WFCTADecodeDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableWFCTADecodeDict();
extern void G__cpp_setup_inheritanceWFCTADecodeDict();
extern void G__cpp_setup_typetableWFCTADecodeDict();
extern void G__cpp_setup_memvarWFCTADecodeDict();
extern void G__cpp_setup_globalWFCTADecodeDict();
extern void G__cpp_setup_memfuncWFCTADecodeDict();
extern void G__cpp_setup_funcWFCTADecodeDict();
extern void G__set_cpp_environmentWFCTADecodeDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "WFCTADecode.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__WFCTADecodeDictLN_TClass;
extern G__linked_taginfo G__WFCTADecodeDictLN_TBuffer;
extern G__linked_taginfo G__WFCTADecodeDictLN_TMemberInspector;
extern G__linked_taginfo G__WFCTADecodeDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__WFCTADecodeDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WFCTADecodeDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__WFCTADecodeDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__WFCTADecodeDictLN_WFCTADecode;
extern G__linked_taginfo G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgR;
extern G__linked_taginfo G__WFCTADecodeDictLN_maplEshortcOintcOlesslEshortgRcOallocatorlEpairlEconstsPshortcOintgRsPgRsPgRcLcLiterator;

/* STUB derived class for protected member access */
